name: Build TWRP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf \
        build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
        libncurses-dev libtinfo-dev lib32z1 lib32stdc++6 libgl1-mesa-dev \
        libxml2-utils xsltproc unzip fontconfig bc python3 python3-pip

    - name: Initialize build environment
      run: |
        source build/envsetup.sh
        lunch twrp_LI6-eng

    - name: Build TWRP
      run: |
        mka adbd vendorbootimage

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-build
        path: out/target/product/LI6/*.img
